fix(clipboard): Fix two crashes
This commit originally comes from a patch applied to CKEditor 4.6.2 on
2017-02-13.

---

This patch short-circuits the `setToolbarStates()` function from CKEditor's
clipboard plugin. See:
https://github.com/ckeditor/ckeditor-dev/blob/4.6.2/plugins/clipboard/plugin.js#L1115

This function creates to bugs (described below), and is not needed, since we
hide the cut/copy/paste buttons from the toolbar.

Bug number 1
------------

This bug happens randomly on production, and from reading the source, it seems
related to copy-pasting:

    TypeError: Cannot read property 'getRanges' of null
    eval at e.exports (https://app.tolteck.com/scripts.69109438fdbd650c721b.bundle.js:1:1), <anonymous> in t at line 655:243
    eval at e.exports (https://app.tolteck.com/scripts.69109438fdbd650c721b.bundle.js:1:1), <anonymous> in r at line 654:517
    eval at e.exports (https://app.tolteck.com/scripts.69109438fdbd650c721b.bundle.js:1:1), <anonymous> in eval at line 647:80
    /vendor.508559905f20e50ff849.bundle.js in r at line 1430:13628
    /vendor.508559905f20e50ff849.bundle.js in t.invokeTask at line 1466:7786
    /vendor.508559905f20e50ff849.bundle.js in Object.onInvokeTask at line 183:2559
    /vendor.508559905f20e50ff849.bundle.js in t.invokeTask at line 1466:7707
    /vendor.508559905f20e50ff849.bundle.js in e.runTask at line 1466:4588
    /vendor.508559905f20e50ff849.bundle.js in invoke at line 1466:8926
    /vendor.508559905f20e50ff849.bundle.js in n.args.(anonymous function) at line 1445:85

I didn't manage to reproduce it on my computer. It is reported at
https://github.com/ckeditor/ckeditor-dev/pull/264 but not merged.

Bug number 2
------------

This one happens only in Firefox, and is randomly triggered when clicking normal
text inputs, after having touched a CKEditor in the past:

    Error: Permission denied to access property "nodeType"
    /scripts.69109438fdbd650c721b.bundle.js line 1 > eval in CKEDITOR.dom.node at line 67:31
    /scripts.69109438fdbd650c721b.bundle.js line 1 > eval in CKEDITOR.dom.selection at line 436:355
    /scripts.69109438fdbd650c721b.bundle.js line 1 > eval in CKEDITOR.editor.prototype.getSelection at line 434:11
    /scripts.69109438fdbd650c721b.bundle.js line 1 > eval in t at line 655:219
    /scripts.69109438fdbd650c721b.bundle.js line 1 > eval in r at line 654:517
    /scripts.69109438fdbd650c721b.bundle.js line 1 > eval in a/</e< at line 647:80
    /vendor.508559905f20e50ff849.bundle.js in r at line 1430:13626
    /vendor.508559905f20e50ff849.bundle.js in x</v</t.prototype.invokeTask at line 1466:7775
    /vendor.508559905f20e50ff849.bundle.js in o</t.prototype.forkInnerZoneWithAngularBehavior/this.inner<.onInvokeTask at line 183:2557
    /vendor.508559905f20e50ff849.bundle.js in x</v</t.prototype.invokeTask at line 1466:7688
    /vendor.508559905f20e50ff849.bundle.js in x</y</e.prototype.runTask at line 1466:4569
    /vendor.508559905f20e50ff849.bundle.js in t/this.invoke at line 1466:8924
    /vendor.508559905f20e50ff849.bundle.js in o/n.args[0] at line 1445:76